package manning.learning.tracingdemo;

import io.jaegertracing.Configuration;
import io.opentracing.Tracer;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;

@SpringBootApplication
public class TracingDemoApplication {

	public static void main(String[] args) {
		SpringApplication.run(TracingDemoApplication.class, args);
	}


	@Bean
	public Tracer jaegerTracer() {
		// The following environment variables need to set
		// JAEGER_ENDPOINT="http://10.42.126.171:28019/api/traces"
		// JAEGER_PROPAGATION="b3"
		// JAEGER_TRACEID_128BIT="true" Use 128bit tracer id to be compatible with the
		// trace id generated by istio/envoy
		System.setProperty("JAEGER_ENDPOINT", "http://127.0.0.1:14268/api/traces");
		System.setProperty("JAEGER_SAMPLER_TYPE","const");
		System.setProperty("JAEGER_SAMPLER_PARAM","1");
		System.setProperty("JAEGER_REPORTER_LOG_SPANS","true");


		return Configuration.fromEnv("eshop-opentracing").getTracer();
	}
}
